-- NOIRSAINT catalog seed generated from the branch's existing catalog.
-- Safe to rerun: existing IDs are preserved.

insert into public.categories (id,name,slug) values
('outerwear','Outerwear','outerwear'),
('leather','Leather','leather'),
('tops','Tops','tops'),
('hoodies','Hoodies','hoodies'),
('bottoms','Bottoms','bottoms'),
('dresses','Dresses','dresses'),
('knitwear','Knitwear','knitwear'),
('accessories','Accessories','accessories'),
('bags','Bags','bags'),
('footwear','Footwear','footwear')
on conflict (id) do nothing;

insert into public.collections (id,name,slug) values
('outerwear','Outerwear','outerwear'),
('essentials','Essentials','essentials'),
('archive','Archive','archive'),
('women','Women','women'),
('accessories','Accessories','accessories'),
('footwear','Footwear','footwear')
on conflict (id) do nothing;

insert into public.products (id,name,slug,sku,category_id,collection_id,brand,base_price,compare_at_price,sale_price,status,featured,new_arrival,bestseller,material,color,gender,style,fit,care_instructions,country_of_production,tags,description,short_description)
values
('p001','Obsidian Coat','obsidian-coat','NS-001','outerwear','outerwear','NOIRSAINT',285,28530,null,'published',true,false,true,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['outerwear','noirsaint','2026'],'Heavy wool-blend coat with a structured NOIRSAINT silhouette.','Heavy wool-blend coat with a structured NOIRSAINT silhouette.'),
('p002','Eclipse Leather Jacket','eclipse-leather-jacket','NS-002','leather','outerwear','NOIRSAINT',420,null,null,'published',true,false,false,'Full-grain leather','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['leather','noirsaint','2026'],'Full-grain leather jacket with a clean architectural cut.','Full-grain leather jacket with a clean architectural cut.'),
('p003','Cathedral Trench','cathedral-trench','NS-003','outerwear','outerwear','NOIRSAINT',360,null,null,'published',true,false,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['outerwear','noirsaint','2026'],'Long technical trench with a dramatic, minimal profile.','Long technical trench with a dramatic, minimal profile.'),
('p004','Void Bomber','void-bomber','NS-004','outerwear','outerwear','NOIRSAINT',275,null,null,'published',true,false,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['outerwear','noirsaint','2026'],'Oversized bomber finished in matte black technical fabric.','Oversized bomber finished in matte black technical fabric.'),
('p005','Signature Tee','signature-tee','NS-005','tops','essentials','NOIRSAINT',85,null,null,'published',true,false,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Relaxed','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['tops','noirsaint','2026'],'The essential NOIRSAINT signature tee.','The essential NOIRSAINT signature tee.'),
('p006','Saint Long Sleeve','saint-long-sleeve','NS-006','tops','essentials','NOIRSAINT',105,10530,null,'published',true,false,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Relaxed','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['tops','noirsaint','2026'],'Heavyweight long sleeve with understated branding.','Heavyweight long sleeve with understated branding.'),
('p007','Frame Shirt','frame-shirt','NS-007','tops','essentials','NOIRSAINT',125,null,null,'published',true,false,true,'Premium cotton blend','Black','Unisex','Contemporary gothic','Relaxed','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['tops','noirsaint','2026'],'Sharp framed shirt designed for layered styling.','Sharp framed shirt designed for layered styling.'),
('p008','Veil Shirt','veil-shirt','NS-008','tops','essentials','NOIRSAINT',135,null,null,'published',true,false,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Relaxed','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['tops','noirsaint','2026'],'Fluid shirt with a soft drape and dark tonal finish.','Fluid shirt with a soft drape and dark tonal finish.'),
('p009','Monolith Hoodie','monolith-hoodie','NS-009','hoodies','essentials','NOIRSAINT',165,null,null,'published',false,true,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Relaxed','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['hoodies','noirsaint','2026'],'Dense cotton hoodie with an oversized fit.','Dense cotton hoodie with an oversized fit.'),
('p010','Chapel Hoodie','chapel-hoodie','NS-010','hoodies','essentials','NOIRSAINT',175,null,null,'published',false,true,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Relaxed','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['hoodies','noirsaint','2026'],'Premium brushed hoodie with a restrained gothic character.','Premium brushed hoodie with a restrained gothic character.'),
('p011','Ash Sweatshirt','ash-sweatshirt','NS-011','tops','essentials','NOIRSAINT',145,14530,null,'published',false,true,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Relaxed','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['tops','noirsaint','2026'],'Relaxed heavyweight sweatshirt in charcoal black.','Relaxed heavyweight sweatshirt in charcoal black.'),
('p012','Obsidian Trousers','obsidian-trousers','NS-012','bottoms','essentials','NOIRSAINT',190,null,null,'published',false,true,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['bottoms','noirsaint','2026'],'Tailored trousers with a straight architectural line.','Tailored trousers with a straight architectural line.'),
('p013','Shadow Cargo','shadow-cargo','NS-013','bottoms','essentials','NOIRSAINT',205,null,null,'published',false,true,true,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['bottoms','noirsaint','2026'],'Utility cargo trousers with a modern wide fit.','Utility cargo trousers with a modern wide fit.'),
('p014','Ruin Denim','ruin-denim','NS-014','bottoms','archive','NOIRSAINT',180,null,null,'published',false,true,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['bottoms','noirsaint','2026'],'Washed black denim with a relaxed silhouette.','Washed black denim with a relaxed silhouette.'),
('p015','Axis Trousers','axis-trousers','NS-015','bottoms','archive','NOIRSAINT',195,null,null,'published',false,true,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['bottoms','noirsaint','2026'],'Minimal trousers with precise panel construction.','Minimal trousers with precise panel construction.'),
('p016','Eclipse Dress','eclipse-dress','NS-016','dresses','women','NOIRSAINT',235,23530,null,'published',false,true,false,'Premium cotton blend','Black','Women','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['dresses','noirsaint','2026'],'A fluid dark dress balancing softness and structure.','A fluid dark dress balancing softness and structure.'),
('p017','Veil Dress','veil-dress','NS-017','dresses','women','NOIRSAINT',225,null,null,'published',false,false,false,'Premium cotton blend','Black','Women','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['dresses','noirsaint','2026'],'Editorial drape dress with a clean neckline.','Editorial drape dress with a clean neckline.'),
('p018','Obsidian Mini Dress','obsidian-mini-dress','NS-018','dresses','women','NOIRSAINT',195,null,null,'published',false,false,false,'Premium cotton blend','Black','Women','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['dresses','noirsaint','2026'],'Compact silhouette with a sharp, minimal finish.','Compact silhouette with a sharp, minimal finish.'),
('p019','Cathedral Knit','cathedral-knit','NS-019','knitwear','essentials','NOIRSAINT',180,null,null,'published',false,false,true,'Wool blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['knitwear','noirsaint','2026'],'Textured knit with a sculpted neckline.','Textured knit with a sculpted neckline.'),
('p020','Halo Cardigan','halo-cardigan','NS-020','knitwear','essentials','NOIRSAINT',165,null,null,'published',false,false,false,'Wool blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['knitwear','noirsaint','2026'],'Soft knit cardigan with elongated proportions.','Soft knit cardigan with elongated proportions.'),
('p021','Relic Leather Vest','relic-leather-vest','NS-021','leather','archive','NOIRSAINT',310,31030,null,'published',false,false,false,'Full-grain leather','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['leather','noirsaint','2026'],'Leather vest with precise utilitarian detailing.','Leather vest with precise utilitarian detailing.'),
('p022','Testament Leather Pants','testament-leather-pants','NS-022','leather','archive','NOIRSAINT',350,null,null,'published',false,false,false,'Full-grain leather','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['leather','noirsaint','2026'],'Tailored leather trousers with a straight leg.','Tailored leather trousers with a straight leg.'),
('p023','Chrome Chain','chrome-chain','NS-023','accessories','accessories','NOIRSAINT',120,null,null,'published',false,false,false,'Premium cotton blend','Silver','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['accessories','noirsaint','2026'],'Polished metal chain designed for everyday layering.','Polished metal chain designed for everyday layering.'),
('p024','Signet Ring','signet-ring','NS-024','accessories','accessories','NOIRSAINT',95,null,null,'published',false,false,false,'Premium cotton blend','Silver','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['accessories','noirsaint','2026'],'Minimal signet ring with a solid sculptural face.','Minimal signet ring with a solid sculptural face.'),
('p025','Relic Pendant','relic-pendant','NS-025','accessories','accessories','NOIRSAINT',110,null,null,'published',false,false,true,'Premium cotton blend','Silver','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['accessories','noirsaint','2026'],'Sculptural pendant on a fine metal chain.','Sculptural pendant on a fine metal chain.'),
('p026','Obsidian Belt','obsidian-belt','NS-026','accessories','accessories','NOIRSAINT',105,10530,null,'published',false,false,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['accessories','noirsaint','2026'],'Full-grain leather belt with tonal hardware.','Full-grain leather belt with tonal hardware.'),
('p027','Void Tote','void-tote','NS-027','bags','accessories','NOIRSAINT',155,null,null,'published',false,false,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['bags','noirsaint','2026'],'Structured everyday tote in matte black.','Structured everyday tote in matte black.'),
('p028','Eclipse Crossbody','eclipse-crossbody','NS-028','bags','accessories','NOIRSAINT',175,null,null,'published',false,false,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['bags','noirsaint','2026'],'Compact crossbody with architectural hardware.','Compact crossbody with architectural hardware.'),
('p029','Monolith Boots','monolith-boots','NS-029','footwear','footwear','NOIRSAINT',285,null,null,'published',false,false,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['footwear','noirsaint','2026'],'Elevated leather boots with a clean monolith sole.','Elevated leather boots with a clean monolith sole.'),
('p030','Axis Loafers','axis-loafers','NS-030','footwear','footwear','NOIRSAINT',250,null,null,'published',false,false,false,'Premium cotton blend','Black','Unisex','Contemporary gothic','Regular','Follow garment label; dry clean leather and structured outerwear.','Designed by NOIRSAINT',ARRAY['footwear','noirsaint','2026'],'Polished leather loafers with a squared profile.','Polished leather loafers with a squared profile.')
on conflict (id) do nothing;

insert into public.product_variants (id,product_id,sku,size_type,size,color,price,sale_price,stock,image_url,status)
values
('p001-black-xs','p001','NS-001-BLA-XS',null,'XS','Black',285,null,5,'/images/products/obsidian-coat-front.png','active'),
('p001-black-s','p001','NS-001-BLA-S',null,'S','Black',285,null,10,'/images/products/obsidian-coat-front.png','active'),
('p001-black-m','p001','NS-001-BLA-M',null,'M','Black',285,null,15,'/images/products/obsidian-coat-front.png','active'),
('p001-black-l','p001','NS-001-BLA-L',null,'L','Black',285,null,12,'/images/products/obsidian-coat-front.png','active'),
('p001-black-xl','p001','NS-001-BLA-XL',null,'XL','Black',285,null,7,'/images/products/obsidian-coat-front.png','active'),
('p002-black-s','p002','NS-002-BLA-S',null,'S','Black',420,null,5,'/images/products/leather-jacket-front.png','active'),
('p002-black-m','p002','NS-002-BLA-M',null,'M','Black',420,null,10,'/images/products/leather-jacket-front.png','active'),
('p002-black-l','p002','NS-002-BLA-L',null,'L','Black',420,null,15,'/images/products/leather-jacket-front.png','active'),
('p002-black-xl','p002','NS-002-BLA-XL',null,'XL','Black',420,null,12,'/images/products/leather-jacket-front.png','active'),
('p003-black-s','p003','NS-003-BLA-S',null,'S','Black',360,null,5,'/images/products/cathedral-trench-front.png','active'),
('p003-black-m','p003','NS-003-BLA-M',null,'M','Black',360,null,10,'/images/products/cathedral-trench-front.png','active'),
('p003-black-l','p003','NS-003-BLA-L',null,'L','Black',360,null,15,'/images/products/cathedral-trench-front.png','active'),
('p003-black-xl','p003','NS-003-BLA-XL',null,'XL','Black',360,null,12,'/images/products/cathedral-trench-front.png','active'),
('p004-black-s','p004','NS-004-BLA-S',null,'S','Black',275,null,5,'/images/products/void-bomber-front.png','active'),
('p004-black-m','p004','NS-004-BLA-M',null,'M','Black',275,null,10,'/images/products/void-bomber-front.png','active'),
('p004-black-l','p004','NS-004-BLA-L',null,'L','Black',275,null,15,'/images/products/void-bomber-front.png','active'),
('p004-black-xl','p004','NS-004-BLA-XL',null,'XL','Black',275,null,12,'/images/products/void-bomber-front.png','active'),
('p004-black-xxl','p004','NS-004-BLA-XXL',null,'XXL','Black',275,null,7,'/images/products/void-bomber-front.png','active'),
('p005-black-xs','p005','NS-005-BLA-XS',null,'XS','Black',85,null,5,'/images/products/signature-tee-front.png','active'),
('p005-black-s','p005','NS-005-BLA-S',null,'S','Black',85,null,10,'/images/products/signature-tee-front.png','active'),
('p005-black-m','p005','NS-005-BLA-M',null,'M','Black',85,null,15,'/images/products/signature-tee-front.png','active'),
('p005-black-l','p005','NS-005-BLA-L',null,'L','Black',85,null,12,'/images/products/signature-tee-front.png','active'),
('p005-black-xl','p005','NS-005-BLA-XL',null,'XL','Black',85,null,7,'/images/products/signature-tee-front.png','active'),
('p005-black-xxl','p005','NS-005-BLA-XXL',null,'XXL','Black',85,null,3,'/images/products/signature-tee-front.png','active'),
('p006-black-xs','p006','NS-006-BLA-XS',null,'XS','Black',105,null,5,'/images/products/saint-long-sleeve-front.png','active'),
('p006-black-s','p006','NS-006-BLA-S',null,'S','Black',105,null,10,'/images/products/saint-long-sleeve-front.png','active'),
('p006-black-m','p006','NS-006-BLA-M',null,'M','Black',105,null,15,'/images/products/saint-long-sleeve-front.png','active'),
('p006-black-l','p006','NS-006-BLA-L',null,'L','Black',105,null,12,'/images/products/saint-long-sleeve-front.png','active'),
('p006-black-xl','p006','NS-006-BLA-XL',null,'XL','Black',105,null,7,'/images/products/saint-long-sleeve-front.png','active'),
('p006-black-xxl','p006','NS-006-BLA-XXL',null,'XXL','Black',105,null,3,'/images/products/saint-long-sleeve-front.png','active'),
('p007-black-s','p007','NS-007-BLA-S',null,'S','Black',125,null,5,'/images/products/frame-shirt-front.png','active'),
('p007-black-m','p007','NS-007-BLA-M',null,'M','Black',125,null,10,'/images/products/frame-shirt-front.png','active'),
('p007-black-l','p007','NS-007-BLA-L',null,'L','Black',125,null,15,'/images/products/frame-shirt-front.png','active'),
('p007-black-xl','p007','NS-007-BLA-XL',null,'XL','Black',125,null,12,'/images/products/frame-shirt-front.png','active'),
('p008-black-s','p008','NS-008-BLA-S',null,'S','Black',135,null,5,'/images/products/veil-shirt-front.png','active'),
('p008-black-m','p008','NS-008-BLA-M',null,'M','Black',135,null,10,'/images/products/veil-shirt-front.png','active'),
('p008-black-l','p008','NS-008-BLA-L',null,'L','Black',135,null,15,'/images/products/veil-shirt-front.png','active'),
('p008-black-xl','p008','NS-008-BLA-XL',null,'XL','Black',135,null,12,'/images/products/veil-shirt-front.png','active'),
('p009-black-xs','p009','NS-009-BLA-XS',null,'XS','Black',165,null,5,'/images/products/monolith-hoodie-front.png','active'),
('p009-black-s','p009','NS-009-BLA-S',null,'S','Black',165,null,10,'/images/products/monolith-hoodie-front.png','active'),
('p009-black-m','p009','NS-009-BLA-M',null,'M','Black',165,null,15,'/images/products/monolith-hoodie-front.png','active'),
('p009-black-l','p009','NS-009-BLA-L',null,'L','Black',165,null,12,'/images/products/monolith-hoodie-front.png','active'),
('p009-black-xl','p009','NS-009-BLA-XL',null,'XL','Black',165,null,7,'/images/products/monolith-hoodie-front.png','active'),
('p009-black-xxl','p009','NS-009-BLA-XXL',null,'XXL','Black',165,null,3,'/images/products/monolith-hoodie-front.png','active'),
('p010-black-s','p010','NS-010-BLA-S',null,'S','Black',175,null,5,'/images/products/chapel-hoodie-front.png','active'),
('p010-black-m','p010','NS-010-BLA-M',null,'M','Black',175,null,10,'/images/products/chapel-hoodie-front.png','active'),
('p010-black-l','p010','NS-010-BLA-L',null,'L','Black',175,null,15,'/images/products/chapel-hoodie-front.png','active'),
('p010-black-xl','p010','NS-010-BLA-XL',null,'XL','Black',175,null,12,'/images/products/chapel-hoodie-front.png','active'),
('p010-black-xxl','p010','NS-010-BLA-XXL',null,'XXL','Black',175,null,7,'/images/products/chapel-hoodie-front.png','active'),
('p011-black-xs','p011','NS-011-BLA-XS',null,'XS','Black',145,null,5,'/images/products/ash-sweatshirt-front.png','active'),
('p011-black-s','p011','NS-011-BLA-S',null,'S','Black',145,null,10,'/images/products/ash-sweatshirt-front.png','active'),
('p011-black-m','p011','NS-011-BLA-M',null,'M','Black',145,null,15,'/images/products/ash-sweatshirt-front.png','active'),
('p011-black-l','p011','NS-011-BLA-L',null,'L','Black',145,null,12,'/images/products/ash-sweatshirt-front.png','active'),
('p011-black-xl','p011','NS-011-BLA-XL',null,'XL','Black',145,null,7,'/images/products/ash-sweatshirt-front.png','active'),
('p011-black-xxl','p011','NS-011-BLA-XXL',null,'XXL','Black',145,null,3,'/images/products/ash-sweatshirt-front.png','active'),
('p012-black-s','p012','NS-012-BLA-S',null,'S','Black',190,null,5,'/images/products/obsidian-trousers-front.png','active'),
('p012-black-m','p012','NS-012-BLA-M',null,'M','Black',190,null,10,'/images/products/obsidian-trousers-front.png','active'),
('p012-black-l','p012','NS-012-BLA-L',null,'L','Black',190,null,15,'/images/products/obsidian-trousers-front.png','active'),
('p012-black-xl','p012','NS-012-BLA-XL',null,'XL','Black',190,null,12,'/images/products/obsidian-trousers-front.png','active'),
('p013-black-s','p013','NS-013-BLA-S',null,'S','Black',205,null,5,'/images/products/shadow-cargo-pants-front.png','active'),
('p013-black-m','p013','NS-013-BLA-M',null,'M','Black',205,null,10,'/images/products/shadow-cargo-pants-front.png','active'),
('p013-black-l','p013','NS-013-BLA-L',null,'L','Black',205,null,15,'/images/products/shadow-cargo-pants-front.png','active'),
('p013-black-xl','p013','NS-013-BLA-XL',null,'XL','Black',205,null,12,'/images/products/shadow-cargo-pants-front.png','active'),
('p013-black-xxl','p013','NS-013-BLA-XXL',null,'XXL','Black',205,null,7,'/images/products/shadow-cargo-pants-front.png','active'),
('p014-black-28','p014','NS-014-BLA-28',null,'28','Black',180,null,5,'/images/products/ruin-denim-front.png','active'),
('p014-black-30','p014','NS-014-BLA-30',null,'30','Black',180,null,10,'/images/products/ruin-denim-front.png','active'),
('p014-black-32','p014','NS-014-BLA-32',null,'32','Black',180,null,15,'/images/products/ruin-denim-front.png','active'),
('p014-black-34','p014','NS-014-BLA-34',null,'34','Black',180,null,12,'/images/products/ruin-denim-front.png','active'),
('p014-black-36','p014','NS-014-BLA-36',null,'36','Black',180,null,7,'/images/products/ruin-denim-front.png','active'),
('p015-black-s','p015','NS-015-BLA-S',null,'S','Black',195,null,5,'/images/products/axis-trousers-front.png','active'),
('p015-black-m','p015','NS-015-BLA-M',null,'M','Black',195,null,10,'/images/products/axis-trousers-front.png','active'),
('p015-black-l','p015','NS-015-BLA-L',null,'L','Black',195,null,15,'/images/products/axis-trousers-front.png','active'),
('p015-black-xl','p015','NS-015-BLA-XL',null,'XL','Black',195,null,12,'/images/products/axis-trousers-front.png','active'),
('p016-black-xs','p016','NS-016-BLA-XS',null,'XS','Black',235,null,5,'/images/products/eclipse-dress-front.png','active'),
('p016-black-s','p016','NS-016-BLA-S',null,'S','Black',235,null,10,'/images/products/eclipse-dress-front.png','active'),
('p016-black-m','p016','NS-016-BLA-M',null,'M','Black',235,null,15,'/images/products/eclipse-dress-front.png','active'),
('p016-black-l','p016','NS-016-BLA-L',null,'L','Black',235,null,12,'/images/products/eclipse-dress-front.png','active'),
('p016-black-xl','p016','NS-016-BLA-XL',null,'XL','Black',235,null,7,'/images/products/eclipse-dress-front.png','active'),
('p017-black-xs','p017','NS-017-BLA-XS',null,'XS','Black',225,null,5,'/images/products/veil-dress-front.png','active'),
('p017-black-s','p017','NS-017-BLA-S',null,'S','Black',225,null,10,'/images/products/veil-dress-front.png','active'),
('p017-black-m','p017','NS-017-BLA-M',null,'M','Black',225,null,15,'/images/products/veil-dress-front.png','active'),
('p017-black-l','p017','NS-017-BLA-L',null,'L','Black',225,null,12,'/images/products/veil-dress-front.png','active'),
('p017-black-xl','p017','NS-017-BLA-XL',null,'XL','Black',225,null,7,'/images/products/veil-dress-front.png','active'),
('p018-black-xs','p018','NS-018-BLA-XS',null,'XS','Black',195,null,5,'/images/products/obsidian-mini-dress-front.png','active'),
('p018-black-s','p018','NS-018-BLA-S',null,'S','Black',195,null,10,'/images/products/obsidian-mini-dress-front.png','active'),
('p018-black-m','p018','NS-018-BLA-M',null,'M','Black',195,null,15,'/images/products/obsidian-mini-dress-front.png','active'),
('p018-black-l','p018','NS-018-BLA-L',null,'L','Black',195,null,12,'/images/products/obsidian-mini-dress-front.png','active'),
('p019-black-xs','p019','NS-019-BLA-XS',null,'XS','Black',180,null,5,'/images/products/cathedral-knit-sweater.png','active'),
('p019-black-s','p019','NS-019-BLA-S',null,'S','Black',180,null,10,'/images/products/cathedral-knit-sweater.png','active'),
('p019-black-m','p019','NS-019-BLA-M',null,'M','Black',180,null,15,'/images/products/cathedral-knit-sweater.png','active'),
('p019-black-l','p019','NS-019-BLA-L',null,'L','Black',180,null,12,'/images/products/cathedral-knit-sweater.png','active'),
('p019-black-xl','p019','NS-019-BLA-XL',null,'XL','Black',180,null,7,'/images/products/cathedral-knit-sweater.png','active'),
('p020-black-xs','p020','NS-020-BLA-XS',null,'XS','Black',165,null,5,'/images/products/halo-cardigan.png','active'),
('p020-black-s','p020','NS-020-BLA-S',null,'S','Black',165,null,10,'/images/products/halo-cardigan.png','active'),
('p020-black-m','p020','NS-020-BLA-M',null,'M','Black',165,null,15,'/images/products/halo-cardigan.png','active'),
('p020-black-l','p020','NS-020-BLA-L',null,'L','Black',165,null,12,'/images/products/halo-cardigan.png','active'),
('p020-black-xl','p020','NS-020-BLA-XL',null,'XL','Black',165,null,7,'/images/products/halo-cardigan.png','active'),
('p021-black-s','p021','NS-021-BLA-S',null,'S','Black',310,null,5,'/images/products/relic-leather-vest.png','active'),
('p021-black-m','p021','NS-021-BLA-M',null,'M','Black',310,null,10,'/images/products/relic-leather-vest.png','active'),
('p021-black-l','p021','NS-021-BLA-L',null,'L','Black',310,null,15,'/images/products/relic-leather-vest.png','active'),
('p021-black-xl','p021','NS-021-BLA-XL',null,'XL','Black',310,null,12,'/images/products/relic-leather-vest.png','active'),
('p022-black-s','p022','NS-022-BLA-S',null,'S','Black',350,null,5,'/images/products/testament-leather-pants.png','active'),
('p022-black-m','p022','NS-022-BLA-M',null,'M','Black',350,null,10,'/images/products/testament-leather-pants.png','active'),
('p022-black-l','p022','NS-022-BLA-L',null,'L','Black',350,null,15,'/images/products/testament-leather-pants.png','active'),
('p022-black-xl','p022','NS-022-BLA-XL',null,'XL','Black',350,null,12,'/images/products/testament-leather-pants.png','active'),
('p023-silver-one-size','p023','NS-023-SIL-ONE-SIZE',null,'ONE SIZE','Silver',120,null,5,'/images/products/chrome-chain.png','active'),
('p024-silver-7','p024','NS-024-SIL-7',null,'7','Silver',95,null,5,'/images/products/signet-ring.png','active'),
('p024-silver-8','p024','NS-024-SIL-8',null,'8','Silver',95,null,10,'/images/products/signet-ring.png','active'),
('p024-silver-9','p024','NS-024-SIL-9',null,'9','Silver',95,null,15,'/images/products/signet-ring.png','active'),
('p024-silver-10','p024','NS-024-SIL-10',null,'10','Silver',95,null,12,'/images/products/signet-ring.png','active'),
('p024-silver-11','p024','NS-024-SIL-11',null,'11','Silver',95,null,7,'/images/products/signet-ring.png','active'),
('p024-silver-12','p024','NS-024-SIL-12',null,'12','Silver',95,null,3,'/images/products/signet-ring.png','active'),
('p025-silver-one-size','p025','NS-025-SIL-ONE-SIZE',null,'ONE SIZE','Silver',110,null,5,'/images/products/relic-pendant.png','active'),
('p026-black-s','p026','NS-026-BLA-S',null,'S','Black',105,null,5,'/images/products/obsidian-belt.png','active'),
('p026-black-m','p026','NS-026-BLA-M',null,'M','Black',105,null,10,'/images/products/obsidian-belt.png','active'),
('p026-black-l','p026','NS-026-BLA-L',null,'L','Black',105,null,15,'/images/products/obsidian-belt.png','active'),
('p026-black-xl','p026','NS-026-BLA-XL',null,'XL','Black',105,null,12,'/images/products/obsidian-belt.png','active'),
('p027-black-one-size','p027','NS-027-BLA-ONE-SIZE',null,'ONE SIZE','Black',155,null,5,'/images/products/void-tote.png','active'),
('p028-black-one-size','p028','NS-028-BLA-ONE-SIZE',null,'ONE SIZE','Black',175,null,5,'/images/products/eclipse-crossbody.png','active'),
('p029-black-38','p029','NS-029-BLA-38',null,'38','Black',285,null,5,'/images/products/monolith-boots.png','active'),
('p029-black-39','p029','NS-029-BLA-39',null,'39','Black',285,null,10,'/images/products/monolith-boots.png','active'),
('p029-black-40','p029','NS-029-BLA-40',null,'40','Black',285,null,15,'/images/products/monolith-boots.png','active'),
('p029-black-41','p029','NS-029-BLA-41',null,'41','Black',285,null,12,'/images/products/monolith-boots.png','active'),
('p029-black-42','p029','NS-029-BLA-42',null,'42','Black',285,null,7,'/images/products/monolith-boots.png','active'),
('p029-black-43','p029','NS-029-BLA-43',null,'43','Black',285,null,3,'/images/products/monolith-boots.png','active'),
('p029-black-44','p029','NS-029-BLA-44',null,'44','Black',285,null,5,'/images/products/monolith-boots.png','active'),
('p029-black-45','p029','NS-029-BLA-45',null,'45','Black',285,null,10,'/images/products/monolith-boots.png','active'),
('p030-black-38','p030','NS-030-BLA-38',null,'38','Black',250,null,5,'/images/products/axis-loafers.png','active'),
('p030-black-39','p030','NS-030-BLA-39',null,'39','Black',250,null,10,'/images/products/axis-loafers.png','active'),
('p030-black-40','p030','NS-030-BLA-40',null,'40','Black',250,null,15,'/images/products/axis-loafers.png','active'),
('p030-black-41','p030','NS-030-BLA-41',null,'41','Black',250,null,12,'/images/products/axis-loafers.png','active'),
('p030-black-42','p030','NS-030-BLA-42',null,'42','Black',250,null,7,'/images/products/axis-loafers.png','active'),
('p030-black-43','p030','NS-030-BLA-43',null,'43','Black',250,null,3,'/images/products/axis-loafers.png','active'),
('p030-black-44','p030','NS-030-BLA-44',null,'44','Black',250,null,5,'/images/products/axis-loafers.png','active'),
('p030-black-45','p030','NS-030-BLA-45',null,'45','Black',250,null,10,'/images/products/axis-loafers.png','active')
on conflict (id) do nothing;

insert into public.product_images (id,product_id,image_url,sort_order,alt_text)
values
('p001-image-1','p001','/images/products/obsidian-coat-front.png',0,'Obsidian Coat'),
('p002-image-1','p002','/images/products/leather-jacket-front.png',0,'Eclipse Leather Jacket'),
('p003-image-1','p003','/images/products/cathedral-trench-front.png',0,'Cathedral Trench'),
('p004-image-1','p004','/images/products/void-bomber-front.png',0,'Void Bomber'),
('p005-image-1','p005','/images/products/signature-tee-front.png',0,'Signature Tee'),
('p006-image-1','p006','/images/products/saint-long-sleeve-front.png',0,'Saint Long Sleeve'),
('p007-image-1','p007','/images/products/frame-shirt-front.png',0,'Frame Shirt'),
('p008-image-1','p008','/images/products/veil-shirt-front.png',0,'Veil Shirt'),
('p009-image-1','p009','/images/products/monolith-hoodie-front.png',0,'Monolith Hoodie'),
('p010-image-1','p010','/images/products/chapel-hoodie-front.png',0,'Chapel Hoodie'),
('p011-image-1','p011','/images/products/ash-sweatshirt-front.png',0,'Ash Sweatshirt'),
('p012-image-1','p012','/images/products/obsidian-trousers-front.png',0,'Obsidian Trousers'),
('p013-image-1','p013','/images/products/shadow-cargo-pants-front.png',0,'Shadow Cargo'),
('p014-image-1','p014','/images/products/ruin-denim-front.png',0,'Ruin Denim'),
('p015-image-1','p015','/images/products/axis-trousers-front.png',0,'Axis Trousers'),
('p016-image-1','p016','/images/products/eclipse-dress-front.png',0,'Eclipse Dress'),
('p017-image-1','p017','/images/products/veil-dress-front.png',0,'Veil Dress'),
('p018-image-1','p018','/images/products/obsidian-mini-dress-front.png',0,'Obsidian Mini Dress'),
('p019-image-1','p019','/images/products/cathedral-knit-sweater.png',0,'Cathedral Knit'),
('p020-image-1','p020','/images/products/halo-cardigan.png',0,'Halo Cardigan'),
('p021-image-1','p021','/images/products/relic-leather-vest.png',0,'Relic Leather Vest'),
('p022-image-1','p022','/images/products/testament-leather-pants.png',0,'Testament Leather Pants'),
('p023-image-1','p023','/images/products/chrome-chain.png',0,'Chrome Chain'),
('p024-image-1','p024','/images/products/signet-ring.png',0,'Signet Ring'),
('p025-image-1','p025','/images/products/relic-pendant.png',0,'Relic Pendant'),
('p026-image-1','p026','/images/products/obsidian-belt.png',0,'Obsidian Belt'),
('p027-image-1','p027','/images/products/void-tote.png',0,'Void Tote'),
('p028-image-1','p028','/images/products/eclipse-crossbody.png',0,'Eclipse Crossbody'),
('p029-image-1','p029','/images/products/monolith-boots.png',0,'Monolith Boots'),
('p030-image-1','p030','/images/products/axis-loafers.png',0,'Axis Loafers')
on conflict (id) do nothing;
