-- NOIRSAINT commerce database layer.
-- This migration is self-contained and contains only fashion-store data and access rules.
-- NOIRSAINT admin foundation.
create table if not exists public.noirsaint_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  is_admin boolean not null default false
);

alter table public.noirsaint_profiles enable row level security;
drop policy if exists "users can read own NOIRSAINT profile" on public.noirsaint_profiles;
create policy "users can read own NOIRSAINT profile"
on public.noirsaint_profiles for select using (auth.uid() = id);

create or replace function public.noirsaint_is_admin()
returns boolean language sql stable security definer set search_path = public
as $
  select coalesce((select is_admin from public.noirsaint_profiles where id = auth.uid()), false);$;

grant select on public.noirsaint_profiles to authenticated;


create table if not exists public.categories (
  id text primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.collections (
  id text primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id text primary key,
  name text not null,
  slug text not null unique,
  sku text,
  category_id text references public.categories(id) on delete set null,
  collection_id text references public.collections(id) on delete set null,
  brand text not null default 'NOIRSAINT',
  base_price numeric(12,2) not null default 0,
  compare_at_price numeric(12,2),
  sale_price numeric(12,2),
  status text not null default 'published' check (status in ('draft','published','archived')),
  featured boolean not null default false,
  new_arrival boolean not null default false,
  bestseller boolean not null default false,
  material text,
  color text,
  gender text,
  style text,
  fit text,
  care_instructions text,
  country_of_production text,
  tags text[] not null default '{}',
  description text,
  short_description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id text primary key,
  product_id text not null references public.products(id) on delete cascade,
  sku text not null unique,
  size_type text,
  size text not null,
  color text,
  price numeric(12,2),
  sale_price numeric(12,2),
  stock integer not null default 0 check (stock >= 0),
  image_url text,
  status text not null default 'active' check (status in ('active','sold_out','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id text primary key,
  product_id text not null references public.products(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  alt_text text,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  shipping_address text,
  shipping_city text,
  shipping_province text,
  payment_method text,
  subtotal numeric(12,2) not null,
  total numeric(12,2) not null,
  status text not null default 'Processing'
    check (status in ('Pending','Confirmed','Processing','Shipped','Delivered','Cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id text references public.products(id) on delete set null,
  variant_id text references public.product_variants(id) on delete set null,
  product_name text not null,
  sku text,
  size text,
  color text,
  unit_price numeric(12,2) not null,
  quantity integer not null check (quantity > 0),
  line_total numeric(12,2) not null
);

create index if not exists product_variants_product_id_idx on public.product_variants(product_id);
create index if not exists product_images_product_id_idx on public.product_images(product_id);
create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

alter table public.categories enable row level security;
alter table public.collections enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.product_images enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "published categories are public" on public.categories;
create policy "published categories are public" on public.categories for select using (true);

drop policy if exists "collections are public" on public.collections;
create policy "collections are public" on public.collections for select using (true);

drop policy if exists "published products are public" on public.products;
create policy "published products are public" on public.products for select using (status = 'published' or public.noirsaint_is_admin());

drop policy if exists "admins manage products" on public.products;
create policy "admins manage products" on public.products for all using (public.noirsaint_is_admin()) with check (public.noirsaint_is_admin());

drop policy if exists "published variants are public" on public.product_variants;
create policy "published variants are public" on public.product_variants for select
using (exists (select 1 from public.products p where p.id = product_id and (p.status = 'published' or public.noirsaint_is_admin())));

drop policy if exists "admins manage variants" on public.product_variants;
create policy "admins manage variants" on public.product_variants for all using (public.noirsaint_is_admin()) with check (public.noirsaint_is_admin());

drop policy if exists "published images are public" on public.product_images;
create policy "published images are public" on public.product_images for select
using (exists (select 1 from public.products p where p.id = product_id and (p.status = 'published' or public.noirsaint_is_admin())));

drop policy if exists "admins manage images" on public.product_images;
create policy "admins manage images" on public.product_images for all using (public.noirsaint_is_admin()) with check (public.noirsaint_is_admin());

drop policy if exists "admins manage categories" on public.categories;
create policy "admins manage categories" on public.categories for all using (public.noirsaint_is_admin()) with check (public.noirsaint_is_admin());

drop policy if exists "admins manage collections" on public.collections;
create policy "admins manage collections" on public.collections for all using (public.noirsaint_is_admin()) with check (public.noirsaint_is_admin());

drop policy if exists "guests can create orders" on public.orders;
create policy "guests can create orders" on public.orders for insert with check (true);

drop policy if exists "users view own orders" on public.orders;
create policy "users view own orders" on public.orders for select using (user_id = auth.uid() or public.noirsaint_is_admin());

drop policy if exists "admins manage orders" on public.orders;
create policy "admins manage orders" on public.orders for update using (public.noirsaint_is_admin()) with check (public.noirsaint_is_admin());

drop policy if exists "admins delete orders" on public.orders;
create policy "admins delete orders" on public.orders for delete using (public.noirsaint_is_admin());

drop policy if exists "users view own order items" on public.order_items;
create policy "users view own order items" on public.order_items for select
using (exists (select 1 from public.orders o where o.id = order_id and (o.user_id = auth.uid() or public.noirsaint_is_admin())));

drop policy if exists "order creators can insert items" on public.order_items;
create policy "order creators can insert items" on public.order_items for insert with check (true);

drop policy if exists "admins manage order items" on public.order_items;
create policy "admins manage order items" on public.order_items for all using (public.noirsaint_is_admin()) with check (public.noirsaint_is_admin());

create or replace function public.create_noirsaint_order(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  order_id text;
  item jsonb;
  current_stock integer;
  uid uuid := auth.uid();
begin
  order_id := coalesce(payload->>'id', 'NS-' || upper(to_hex(floor(extract(epoch from clock_timestamp()) * 1000)::bigint)));

  insert into public.orders (
    id, user_id, customer_name, customer_email, customer_phone,
    shipping_address, shipping_city, shipping_province,
    payment_method, subtotal, total, status
  ) values (
    order_id, uid, payload->'customer'->>'name', payload->'customer'->>'email',
    payload->'customer'->>'phone', payload->'customer'->>'address',
    payload->'customer'->>'city', payload->'customer'->>'province',
    payload->'customer'->>'payment', (payload->>'total')::numeric,
    (payload->>'total')::numeric, 'Processing'
  );

  for item in select * from jsonb_array_elements(payload->'items')
  loop
    select stock into current_stock
    from public.product_variants
    where id = item->>'variantId'
    for update;

    if current_stock is null then
      raise exception 'Variant % does not exist', item->>'variantId';
    end if;

    if current_stock < (item->>'quantity')::integer then
      raise exception 'Insufficient stock for variant %', item->>'variantId';
    end if;

    update public.product_variants
    set stock = stock - (item->>'quantity')::integer,
        status = case when stock - (item->>'quantity')::integer > 0 then 'active' else 'sold_out' end,
        updated_at = now()
    where id = item->>'variantId';

    insert into public.order_items (
      order_id, product_id, variant_id, product_name, sku, size, color,
      unit_price, quantity, line_total
    ) values (
      order_id, item->>'productId', item->>'variantId', item->>'name',
      item->>'sku', item->>'size', item->>'color',
      (item->>'price')::numeric, (item->>'quantity')::integer,
      ((item->>'price')::numeric * (item->>'quantity')::integer)
    );
  end loop;

  return jsonb_build_object('id', order_id, 'status', 'Processing');
end;
$$;

grant execute on function public.create_noirsaint_order(jsonb) to anon, authenticated;

create or replace function public.set_noirsaint_variant_stock(p_variant_id text, p_stock integer)
returns public.product_variants
language plpgsql
security definer
set search_path = public
as $$
declare result public.product_variants;
begin
  if not public.noirsaint_is_admin() then raise exception 'Admin access required'; end if;
  if p_stock < 0 then raise exception 'Stock cannot be negative'; end if;
  update public.product_variants
  set stock = p_stock,
      status = case when p_stock > 0 then 'active' else 'sold_out' end,
      updated_at = now()
  where id = p_variant_id
  returning * into result;
  if result.id is null then raise exception 'Variant not found'; end if;
  return result;
end;
$$;

grant execute on function public.set_noirsaint_variant_stock(text, integer) to authenticated;

grant select on public.categories, public.collections, public.products, public.product_variants, public.product_images to anon, authenticated;
grant insert on public.orders, public.order_items to anon, authenticated;
grant select, update, delete on public.orders to authenticated;
grant select on public.order_items to authenticated;
grant insert, update, delete on public.products, public.product_variants, public.product_images, public.categories, public.collections to authenticated;
